import type { FunctionItem } from "../types/app";

export const FUNCTION_REGISTRY: FunctionItem[] = [
  {
    id: "camera.receive_frame",
    area: "Camera",
    label: "Receive device frame",
    description: "Accept the latest JPEG or PNG uploaded by an ESP32 or Raspberry Pi camera node.",
    status: "implemented",
  },
  {
    id: "camera.preview_stream",
    area: "Camera",
    label: "Preview latest frame",
    description: "Automatically display new camera frames and connection metadata.",
    status: "implemented",
  },
  {
    id: "camera.simulation",
    area: "Camera",
    label: "Simulate camera frames",
    description: "Generate moving test frames without requiring camera hardware.",
    status: "implemented",
  },
  {
    id: "inference.load_model",
    area: "AI inference",
    label: "Load detection model",
    description: "Discover local trained models and load either a selected model or the newest/default model.",
    status: "implemented",
  },
  {
    id: "inference.manage_models",
    area: "AI inference",
    label: "Choose, default, and delete trained models",
    description: "Review local outputs/training runs, choose which model to run, set the default auto-load model, and delete outdated model folders.",
    status: "implemented",
  },
  {
    id: "inference.visibility",
    area: "AI inference",
    label: "Visibility controls",
    description: "Adjust backend confidence down to 1%, toggle overlay boxes/labels, and filter visible classes on the live canvas.",
    status: "implemented",
  },
  {
    id: "inference.run_frame",
    area: "AI inference",
    label: "Run detection on frame",
    description: "Run the loaded trained model on receiver or simulation frames and return original-coordinate boxes.",
    status: "implemented",
  },
  {
    id: "zones.edit",
    area: "Zones",
    label: "Edit traffic zones",
    description: "Draw and edit polygons for waiting, crossing, vehicle queue, and ignore zones.",
    status: "placeholder",
  },
  {
    id: "zones.count",
    area: "Zones",
    label: "Count objects in zones",
    description: "Map detections to traffic zones using object center or box overlap.",
    status: "placeholder",
  },
  {
    id: "traffic.decide",
    area: "Traffic logic",
    label: "Make signal decision",
    description: "Use counts, wait time, and crossing safety rules to simulate light phases.",
    status: "placeholder",
  },
  {
    id: "dataset.capture",
    area: "Dataset",
    label: "Capture frame and metadata",
    description: "Save the latest receiver or simulation image with source metadata, quality tag, and notes.",
    status: "implemented",
  },
  {
    id: "dataset.review",
    area: "Dataset",
    label: "Review and label captured data",
    description: "Browse saved frames, draw manual bounding boxes, save reviewed negatives, and exclude bad captures from training builds.",
    status: "implemented",
  },
  {
    id: "dataset.yolo_build",
    area: "Dataset",
    label: "Build managed YOLO dataset",
    description: "Convert reviewed captures into distinct YOLO train/validation images, labels, and yolo/data.yaml.",
    status: "implemented",
  },
  {
    id: "training.run",
    area: "Training",
    label: "Start training run",
    description: "Validate a labeled YOLO dataset and launch an optional Ultralytics training run.",
    status: "implemented",
  },
  {
    id: "model.export",
    area: "Model",
    label: "Export runtime package",
    description: "Later: export model, class list, thresholds, and preprocessing config.",
    status: "later",
  },
  {
    id: "logs.inspect",
    area: "Debug",
    label: "Inspect logs and error codes",
    description: "View recent errors, request IDs, and related module scope.",
    status: "placeholder",
  },
];
