import type { FunctionItem } from "../types/app";

export const FUNCTION_REGISTRY: FunctionItem[] = [
  { id: "camera.receive_frame", area: "Camera", label: "Receive device frame", description: "Accept the latest JPEG or PNG uploaded by an ESP32 or Raspberry Pi camera node.", status: "implemented" },
  { id: "camera.preview_stream", area: "Camera", label: "Preview latest frame", description: "Automatically display new camera frames and connection metadata.", status: "implemented" },
  { id: "camera.simulation", area: "Camera", label: "Simulate camera frames", description: "Generate varied traffic test frames with top-to-bottom pedestrians, horizontal vehicles, and a vertical crossing.", status: "implemented" },
  { id: "camera.simulation_density", area: "Camera", label: "Adjust simulation density", description: "Switch the synthetic scene between light, normal, and busy pedestrian/vehicle populations.", status: "implemented" },
  { id: "camera.simulation_pause", area: "Camera", label: "Pause simulation scene", description: "Freeze and resume one synthetic frame for inspection or persistent dataset capture.", status: "implemented" },
  { id: "inference.load_model", area: "AI inference", label: "Load detection model", description: "Discover local trained models and load either a selected model or the newest/default model.", status: "implemented" },
  { id: "inference.manage_models", area: "AI inference", label: "Choose, default, and delete trained models", description: "Review local outputs/training runs, choose which model to run, set the default auto-load model, and delete outdated model folders.", status: "implemented" },
  { id: "inference.visibility", area: "AI inference", label: "Visibility controls", description: "Adjust backend confidence down to 1%, toggle overlay boxes/labels, and filter visible classes on the live canvas.", status: "implemented" },
  { id: "inference.run_frame", area: "AI inference", label: "Run detection on frame", description: "Run the loaded trained model on receiver or simulation frames and return original-coordinate boxes.", status: "implemented" },
  { id: "zones.edit", area: "Zones", label: "Edit camera-aligned traffic zones", description: "Draw, edit, validate, save, load, and reset waiting, crossing, queue, and ignore polygons directly over the current camera feed.", status: "implemented" },
  { id: "zones.live_overlay", area: "Zones", label: "Overlay zones on Live AI", description: "Scale persisted zone polygons into the active camera resolution and display them with live detections.", status: "implemented" },
  { id: "zones.count", area: "Zones", label: "Count live detections in zones", description: "Scale detection centres into the zone reference frame and count people/vehicles in configured zones.", status: "implemented" },
  { id: "traffic.decide", area: "Traffic logic", label: "Generate simulation recommendation", description: "Use live zone counts to produce a bounded, simulation-only phase recommendation with an auditable reason.", status: "implemented" },
  { id: "traffic.live_signal", area: "Traffic logic", label: "Live AI signal overlay", description: "Show the current simulation-only traffic phase as a compact signal in the top-right of Live AI.", status: "implemented" },
  { id: "dataset.capture", area: "Dataset", label: "Capture frame and metadata", description: "Save the latest receiver or simulation image with source metadata, quality tag, and notes.", status: "implemented" },
  { id: "dataset.review", area: "Dataset", label: "Review, delete, and label captured data", description: "Browse or delete saved frames, draw manual bounding boxes, save reviewed negatives, and exclude bad captures from training builds.", status: "implemented" },
  { id: "dataset.delete", area: "Dataset", label: "Delete captured image", description: "Permanently remove one capture image together with its paired metadata and saved manual labels.", status: "implemented" },
  { id: "dataset.yolo_build", area: "Dataset", label: "Build managed YOLO dataset", description: "Convert reviewed captures into distinct YOLO train/validation images, labels, and yolo/data.yaml.", status: "implemented" },
  { id: "training.run", area: "Training", label: "Start training run", description: "Validate a labeled YOLO dataset and launch a local Ultralytics training run.", status: "implemented" },
  { id: "training.convergence", area: "Training", label: "Monitor convergence", description: "Plot per-epoch validation fitness and mAP50-95 while training is running.", status: "implemented" },
  { id: "training.early_stop", area: "Training", label: "Automatic early stopping", description: "Stop training automatically when validation fitness fails to improve for the configured patience window.", status: "implemented" },
  { id: "settings.runtime", area: "Debug", label: "Persist runtime settings", description: "Apply default confidence, camera-status polling, training patience, and backend log level without editing source code.", status: "implemented" },
  { id: "logs.inspect", area: "Debug", label: "Inspect real backend logs", description: "View recent real backend records with level, module scope, request ID, and error code when present.", status: "implemented" },
  { id: "model.export", area: "Model", label: "Export runtime package", description: "Later: export model, class list, thresholds, and preprocessing config.", status: "later" },
];
